plugin:
    name: 'brenodouglasaraujosouza.brcommerce::lang.plugin.name'
    description: 'brenodouglasaraujosouza.brcommerce::lang.plugin.description'
    author: BrenoDouglasAraujoSouza
    icon: oc-icon-shopping-cart
    homepage: ''
navigation:
    main-menu-item:
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.catalog'
        url: /
        icon: icon-tag
        sideMenu:
            side-menu-item:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.categories'
                url: /
                icon: icon-tags
                permissions:
                    - brcommerce.catalog.categories
            side-menu-item2:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.products'
                url: /
                icon: icon-tags
                permissions:
                    - brcommerce.catalog.products
            side-menu-item3:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.options'
                url: /
                icon: icon-tags
                permissions:
                    - brcommerce.catalog.options
            side-menu-item4:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.manufactures'
                url: /
                icon: icon-tags
                permissions:
                    - brcommerce.catalog.manufacture
            side-menu-item5:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.reviews'
                url: /
                icon: icon-tags
                permissions:
                    - brcommerce.catalog.reviews
            side-menu-item6:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.information'
                url: /
                icon: icon-tags
                permissions:
                    - brcommerce.catalog.information
    main-menu-item2:
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.sales'
        url: /
        icon: icon-shopping-cart
        permissions:
            - 'br.commerce.sales.*'
        sideMenu:
            side-menu-item:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.orders'
                url: /
                icon: icon-shopping-cart
            side-menu-item2:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.invoices'
                url: /
                icon: icon-shopping-cart
            side-menu-item3:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.returns'
                url: /
                icon: icon-shopping-cart
    main-menu-item3:
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.customer'
        url: /
        icon: icon-user
        sideMenu:
            side-menu-item:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.customers'
                url: /
                icon: icon-user
            side-menu-item2:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.groups'
                url: /
                icon: icon-user
    main-menu-item4:
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.marketing'
        url: /
        icon: icon-share-alt
        sideMenu:
            side-menu-item:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.campaigns'
                url: /
                icon: icon-share-alt
                permissions:
                    - brcommerce.marketing.campaigns
            side-menu-item2:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.Affiliates'
                url: /
                icon: icon-share-alt
                permissions:
                    - brcommerce.marketing.affiliates
            side-menu-item3:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.coupons'
                url: /
                icon: icon-share-alt
                permissions:
                    - brcommerce.marketing.coupons
            side-menu-item4:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.vouchers'
                url: /
                icon: icon-share-alt
                permissions:
                    - brcommerce.marketing.vourches
    main-menu-item5:
        label: Report
        url: /
        icon: icon-area-chart
        sideMenu:
            side-menu-item:
                label: 'Menu Item'
                url: /
                icon: icon-area-chart
            side-menu-item2:
                label: 'Menu Item'
                url: /
                icon: icon-area-chart
            side-menu-item3:
                label: 'Menu Item'
                url: /
                icon: icon-area-chart
            side-menu-item4:
                label: 'Menu Item'
                url: /
                icon: icon-area-chart
permissions:
    brcommerce.catalog.categories:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.permissions.catalog'
        label: 'brenodouglasaraujosouza.brcommerce::lang.permissions.label.categories'
    brcommerce.catalog.products:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.permissions.catalog'
        label: 'brenodouglasaraujosouza.brcommerce::lang.permissions.label.products'
    brcommerce.catalog.options:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.permissions.catalog'
        label: 'brenodouglasaraujosouza.brcommerce::lang.permissions.label.options'
    brcommerce.catalog.reviews:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.permissions.catalog'
        label: 'brenodouglasaraujosouza.brcommerce::lang.permissions.label.reviews'
    brcommerce.catalog.information:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.permissions.catalog'
        label: 'brenodouglasaraujosouza.brcommerce::lang.permissions.label.information'
    brcommerce.catalog.manufacture:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.permissions.catalog'
        label: 'brenodouglasaraujosouza.brcommerce::lang.permissions.label.manufacture'
    brcommerce.sales.orders:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.sales'
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.orders'
    brcommerce.sales.invoices:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.sales'
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.invoices'
    brcommerce.sales.returns:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.sales'
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.returns'
    brcommerce.marketing.campaigns:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.marketing'
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.campaigns'
    brcommerce.marketing.affiliates:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.marketing'
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.Affiliates'
    brcommerce.marketing.vourches:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.marketing'
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.vouchers'
    brcommerce.marketing.coupons:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.marketing'
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.coupons'
