plugin:
    name: 'brenodouglasaraujosouza.brcommerce::lang.plugin.name'
    description: 'brenodouglasaraujosouza.brcommerce::lang.plugin.description'
    author: BrenoDouglasAraujoSouza
    icon: oc-icon-shopping-cart
    homepage: ''
navigation:
    catalog:
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.catalog'
        url: brenodouglasaraujosouza/brcommerce/category
        icon: icon-tag
        sideMenu:
            category:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.categories'
                url: brenodouglasaraujosouza/brcommerce/category
                icon: icon-tags
                permissions:
                    - brcommerce.catalog.categories
            product:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.products'
                url: brenodouglasaraujosouza/brcommerce/product
                icon: icon-tags
                permissions:
                    - brcommerce.catalog.products
            manufacture:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.manufactures'
                url: brenodouglasaraujosouza/brcommerce/manufacture
                icon: icon-tags
                permissions:
                    - brcommerce.catalog.manufacture
            reviews:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.reviews'
                url: brenodouglasaraujosouza/brcommerce/review
                icon: icon-tags
                permissions:
                    - brcommerce.catalog.reviews
            information:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.information'
                url: brenodouglasaraujosouza/brcommerce/information
                icon: icon-tags
                permissions:
                    - brcommerce.catalog.information
            banner:
                label: Banner
                url: brenodouglasaraujosouza/brcommerce/banner
                icon: icon-tags
    sales:
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.sales'
        url: /
        icon: icon-shopping-cart
        permissions:
            - 'br.commerce.sales.*'
        sideMenu:
            order:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.orders'
                url: brenodouglasaraujosouza/brcommerce/order
                icon: icon-shopping-cart
            invoice:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.invoices'
                url: brenodouglasaraujosouza/brcommerce/invoice
                icon: icon-shopping-cart
            return:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.returns'
                url: brenodouglasaraujosouza/brcommerce/return
                icon: icon-shopping-cart
    customer:
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.customer'
        url: brenodouglasaraujosouza/brcommerce/customer
        icon: icon-user
        sideMenu:
            customer:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.customers'
                url: brenodouglasaraujosouza/brcommerce/customer
                icon: icon-user
            group:
                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.groups'
                url: brenodouglasaraujosouza/brcommerce/customerGroup
                icon: icon-user
#    main-menu-item4:
#        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.marketing'
#        url: /
#        icon: icon-share-alt
#        sideMenu:
#            side-menu-item:
#                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.campaigns'
#                url: /
#                icon: icon-share-alt
#                permissions:
#                    - brcommerce.marketing.campaigns
#            side-menu-item2:
#                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.Affiliates'
#                url: /
#                icon: icon-share-alt
#                permissions:
#                    - brcommerce.marketing.affiliates
#            side-menu-item3:
#                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.coupons'
#                url: /
#                icon: icon-share-alt
#                permissions:
#                    - brcommerce.marketing.coupons
#            side-menu-item4:
#                label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.vouchers'
#                url: /
#                icon: icon-share-alt
#                permissions:
#                    - brcommerce.marketing.vourches
#    main-menu-item5:
#        label: Report
#        url: /
#        icon: icon-area-chart
#        sideMenu:
#            side-menu-item:
#                label: 'Menu Item'
#                url: /
#                icon: icon-area-chart
#            side-menu-item2:
#                label: 'Menu Item'
#                url: /
#                icon: icon-area-chart
#            side-menu-item3:
#                label: 'Menu Item'
#                url: /
#                icon: icon-area-chart
#            side-menu-item4:
#                label: 'Menu Item'
#                url: /
#                icon: icon-area-chart
permissions:
    brcommerce.catalog.categories:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.permissions.catalog'
        label: 'brenodouglasaraujosouza.brcommerce::lang.permissions.label.categories'
    brcommerce.catalog.products:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.permissions.catalog'
        label: 'brenodouglasaraujosouza.brcommerce::lang.permissions.label.products'
    brcommerce.catalog.options:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.permissions.catalog'
        label: 'brenodouglasaraujosouza.brcommerce::lang.permissions.label.options'
    brcommerce.catalog.reviews:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.permissions.catalog'
        label: 'brenodouglasaraujosouza.brcommerce::lang.permissions.label.reviews'
    brcommerce.catalog.information:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.permissions.catalog'
        label: 'brenodouglasaraujosouza.brcommerce::lang.permissions.label.information'
    brcommerce.catalog.manufacture:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.permissions.catalog'
        label: 'brenodouglasaraujosouza.brcommerce::lang.permissions.label.manufacture'
    brcommerce.sales.orders:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.sales'
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.orders'
    brcommerce.sales.invoices:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.sales'
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.invoices'
    brcommerce.sales.returns:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.sales'
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.returns'
    brcommerce.marketing.campaigns:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.marketing'
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.campaigns'
    brcommerce.marketing.affiliates:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.marketing'
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.Affiliates'
    brcommerce.marketing.vourches:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.marketing'
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.vouchers'
    brcommerce.marketing.coupons:
        tab: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.marketing'
        label: 'brenodouglasaraujosouza.brcommerce::lang.menu.item.label.coupons'
