list: $/brenodouglasaraujosouza/brcommerce/models/review/columns.yaml
modelClass: BrenoDouglasAraujoSouza\BrCommerce\Models\Review
title: Review
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'brenodouglasaraujosouza/brcommerce/review/update/:id'
