list: $/brenodouglasaraujosouza/brcommerce/models/manufacture/columns.yaml
modelClass: BrenoDouglasAraujoSouza\BrCommerce\Models\Manufacture
title: Manufacture
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'brenodouglasaraujosouza/brcommerce/manufacture/update/:id'
