list: $/brenodouglasaraujosouza/brcommerce/models/product/columns.yaml
modelClass: BrenoDouglasAraujoSouza\BrCommerce\Models\Product
title: Product
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'brenodouglasaraujosouza/brcommerce/product/update/:id'
