list: $/brenodouglasaraujosouza/brcommerce/models/information/columns.yaml
modelClass: BrenoDouglasAraujoSouza\BrCommerce\Models\Information
title: Information
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'brenodouglasaraujosouza/brcommerce/information/update/:id'
